language: node_js
sudo: required
dist: trusty
node_js:
  - 'node'

addons:
  code_climate:
    repo_token: 8b2790e99fb9db4d56209c72af8f1087062b5eea27ee63c1056179d4c9e4f38d
    chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install codeclimate-test-reporter

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

after_script:
- codeclimate-test-reporter < coverage/lcov.info
